[package]
name = "httpserver"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "http-lib",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http-lib = { path = "./http-lib" }
